### ISSUE TITLE
Feature request: Return error code when `phinder test` is failed

### ISSUE THREAD

**Issue by wata727** [tomokinakamaru/phinder#15]
Currently, It seems that `phinder test` always returns `0` as exit status even if tests are failed.

```yaml
- id: sample.var_dump
  pattern: var_dump(...)
  message: Do not use var_dump.
  justification: Allowed when debugging

- id: sample.in_array_without_3rd_param
  pattern: in_array(?, ?)
  message: Specify 3rd parameter explicitly when calling in_array to avoid unexpected comparison results.
  before:
    - in_array(1, $arr)
    - in_array(2, $arr, true) # invalid pattern!
  after:
    - in_array(3, $arr, true)
    - in_array(4, $arr, false)
```

```
% bin/phinder test -r sample/phinder.yml
`in_array(2, $arr, true)` does not match the rule sample.in_array_without_3rd_param but should match that rule.
% echo $? 
0   
```

However, when running on CI etc., I think that it is useful to be able to distinguish by returning the exit status as non-zero. What do you think?
