### ISSUE TITLE
Redesign config structure about test feature

### ISSUE THREAD

**Issue by wata727** [tomokinakamaru/phinder#16]
Pattern tests are written as follows, but the top level `before` and `after` attributes make me confused.

```yaml
- id: sample.in_array_without_3rd_param
  pattern: in_array(?, ?)
  message: Specify 3rd parameter explicitly when calling in_array to avoid unexpected comparison results.
  before:
    - in_array(1, $arr)
    - in_array(2, $arr) 
  after:
    - in_array(3, $arr, true)
    - in_array(4, $arr, false)
```

For example, Querly allows you to write `examples`as top level like the following:

```yaml
- ...
  examples:
    - before: in_array(1, $arr)
      after: in_array(3, $arr, true)
    - before: in_array(2, $arr)
      after: in_array(4, $arr, false)
```

In this way, I would like to express that writing tests as a structure of YAML like the following. Please tell me your opinion.

```yaml
- ...
  test:
    fail:
      - in_array(1, $arr)
      - in_array(2, $arr)
    pass:
      - in_array(3, $arr, true)
      - in_array(4, $arr, false)
```
