### ISSUE TITLE
Invalid pattern found in dangerous_eval in phinder.yaml: eval

### ISSUE THREAD

**Issue by wata727** [tomokinakamaru/phinder#26]
The following is reproduction step:

```
% phinder -r phinder.yaml                                                                                                                                     
Invalid pattern found in dangerous_eval in phinder.yaml: eval
```

```yaml
- id: dangerous_eval
  pattern: eval
  message: |
    The eval() language construct is very dangerous

    If you have carefully verified that there is no other option than to use this construct,
    pay special attention not to pass any user provided data into it without properly validating it beforehand.
```

Is this the intended behavior? Or is it a bug?
